"""birthdate (User), rating(Book)

Revision ID: aaff8baecb27
Revises: c9349975ef2b
Create Date: 2023-12-04 21:01:30.966620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaff8baecb27'
down_revision: Union[str, None] = 'c9349975ef2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('birth_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birth_date')
    op.drop_column('book', 'rating')
    # ### end Alembic commands ###
