"""added rating  to the Book model

Revision ID: c0a3c6ae48bb
Revises: d57a83415b3a
Create Date: 2023-12-04 11:51:48.114150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a3c6ae48bb'
down_revision: Union[str, None] = 'd57a83415b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'rating')
    # ### end Alembic commands ###
