"""del rating

Revision ID: c9349975ef2b
Revises: 54b4e1410c25
Create Date: 2023-12-04 20:55:58.651330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9349975ef2b'
down_revision: Union[str, None] = '54b4e1410c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('rating', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
